### PR TITLE
Support released mongoid 6.0.0

### PR DESCRIPTION
**Pull request by chocoken517**

### CODE REVIEW

**Comment by L-Oto** [comment]
As far as I can tell, the PR looks 👍 
I'd be great if you could merge this soon because I need it. Thank you!

**Comment by ivanovaleksey** [comment]
Hi guys!
What about this PR?

**Comment by mathiasAichinger** [comment]
Also using it already. Looks fine 👍

**Comment by ivanovaleksey** [comment]
The gem maintainers seems to have no activity for a couple months. :disappointed:

**Comment by leandrost** [comment]
@rodrigopinto my man, could you please? :sweat_smile:

**Comment by exAspArk** [comment]
Any plans to release it to rubygems?

**Pull request merged**
