### PR TITLE
Support for just released mongoid 5.0.0

### PR DESCRIPTION
**Pull request by 90yukke**

### CODE REVIEW

**Comment by rodrigopinto** [comment]
Hey @90yukke let's move the gem to 3.0.0 and keep major versions responsible for different mongoid version. I will yank the old version for beta support. :)

**Comment by 90yukke** [comment]
@rodrigopinto updated

**Comment by rodrigopinto** [comment]
@90yukke can you squash the commits, so I'll merge and release today asap.

**Comment by 90yukke** [comment]
@rodrigopinto done

**Comment by rodrigopinto** [comment]
Thanks @90yukke ! :+1: :smile:

**Comment by mkempe** [comment]
Many thanks @90yukke and @rodrigopinto !

**Comment by rodrigopinto** [comment]
@mkempe  @90yukke :smile: :+1:

**Pull request merged**
