### PR TITLE
Support Mongoid 5.0.0.rc0

### PR DESCRIPTION
**Pull request by mkempe**
Hey there,

first of all, thanks for `mongoid-rspec`.

This is the following request to #154, to support Mongoid 5.0.0.rc0.

### CODE REVIEW

**Comment by rodrigopinto** [comment]
Hey @mkempe thanks! :) Could you squash the commits to merge? 

Thanks.

**Comment by mkempe** [comment]
Hey @rodrigopinto,

done, thanks again for mongoid-rspec.

Maik

**Comment by rodrigopinto** [comment]
@mkempe Thanks a lot! :+1: :fireworks:

**Comment by dblock** [comment]
Added to a list at http://code.dblock.org/2015/07/24/getting-things-done-with-mongoid-5.html. If anyone has interest in supporting multiple versions of Mongoid with mongoid-rspec (aka being backward compatible) lmk I can PR that.

**Comment by rodrigopinto** [comment]
Hey @dblock thanks! :+1: :smiley: 

Currently we do the backward support based on mongoid-rspec versions. We would be on 3.0.0 to support mongoid 5.0.0, but it's on 2.3.0.rc0. To be be honest I'm not having enough time and I'm not dedicating efforts to support the gem.

If you have any suggestion or PR that could help we improve the gem. I would appreciate it. 

Thanks,
Rodrigo

**Pull request merged**
